#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Oct  2 17:58:55 2024

@author: david
"""

#%%
# packages used
import numpy as np
import matplotlib.pyplot as plt

#%% Question 1

size = 10 # 
N = 2**size
h = 1/N
rand = np.sqrt(h)*np.random.randn(N)

brown = [None] * size

num = 0
for i in range(0, size):
    div = 2**i
    M = int(N/div)
    result = np.empty([M,1])
    
    for j in range(0,M):
        num += sum(rand[div*j : div*j+div]) # add the appropriate sampled values together for lower resolutions
        result[j] = num
    
    brown[i] = result
    num = 0

for i in range(0,len(brown)):
    brown[i] = np.append(0,brown[i])
    M = len(brown[i])
    plt.plot(np.linspace(0,1,M), brown[i])
plt.xlabel("(t)")
plt.ylabel("X(t)")
